#!/usr/bin/env node

/**
 * AMO V2 Validation Test Runner
 * 
 * Usage:
 *   npm run validate:v2
 *   or
 *   node tests/materiality-signal-validation/run-validation.js
 */

import { ValidationRunner } from './validation-runner';
import { writeFileSync } from 'fs';

async function runValidation() {
  console.log('🚀 Starting AMO V2 Materiality Signal Validation...\n');
  
  // Check if V2 pipeline is enabled
  const useV2Pipeline = process.env.USE_MATERIALITY_SIGNAL_PIPELINE === 'true';
  
  if (!useV2Pipeline) {
    console.log('⚠️  WARNING: USE_MATERIALITY_SIGNAL_PIPELINE is not set to true');
    console.log('📝 Setting USE_MATERIALITY_SIGNAL_PIPELINE=true for validation...\n');
    process.env.USE_MATERIALITY_SIGNAL_PIPELINE = 'true';
  }
  
  try {
    const runner = new ValidationRunner();
    const report = await runner.runAllTests();
    
    // Generate markdown report
    const markdownReport = generateMarkdownReport(report);
    
    // Save report to file
    const reportPath = 'validation-report.md';
    writeFileSync(reportPath, markdownReport);
    
    console.log(`\n📄 Validation report saved to: ${reportPath}`);
    console.log('\n🎯 Validation complete!');
    
    // Exit with appropriate code
    if (report.failed_tests === 0) {
      console.log('✅ All tests passed!');
      process.exit(0);
    } else {
      console.log(`❌ ${report.failed_tests} test(s) failed`);
      process.exit(1);
    }
    
  } catch (error) {
    console.error('💥 Validation failed:', error);
    process.exit(1);
  }
}

function generateMarkdownReport(report: any): string {
  const timestamp = new Date().toISOString();
  
  return `# AMO V2 Materiality Signal Validation Report

**Generated:** ${timestamp}
**Total Tests:** ${report.total_tests}
**Passed:** ${report.passed_tests} ✅
**Failed:** ${report.failed_tests} ❌
**Overall Accuracy:** ${(report.overall_accuracy * 100).toFixed(1)}%

## 📊 Accuracy Metrics

| Metric | Score |
|--------|-------|
| Signal Accuracy | ${(report.signal_accuracy * 100).toFixed(1)}% |
| AIDMA Accuracy | ${(report.aidma_accuracy * 100).toFixed(1)}% |
| Relevance Accuracy | ${(report.relevance_accuracy * 100).toFixed(1)}% |
| Evidence Quality | ${(report.evidence_quality_score * 100).toFixed(1)}% |
| Avg Processing Time | ${report.average_processing_time.toFixed(0)}ms |

## 🧪 Test Results

${report.results.map((result: any) => generateTestResultSection(result)).join('\n')}

## 📋 Summary

${report.summary}

## 🔍 Analysis

### Signal Detection Performance
${generateSignalAnalysis(report.results)}

### AIDMA Mapping Performance  
${generateAIDMAAnalysis(report.results)}

### Evidence Quality Assessment
${generateEvidenceAnalysis(report.results)}

## 🚦 Recommendations

${generateRecommendations(report)}

---

*Report generated by AMO V2 Validation Harness*
`;
}

function generateTestResultSection(result: any): string {
  const status = result.error ? '❌ ERROR' : 
    (result.actual_primary_signal === result.test_case.expected_primary_signal ? '✅ PASS' : '❌ FAIL');
  
  return `
### ${result.test_case.name} ${status}

**Source:** [${result.test_case.name}](${result.test_case.source_url})

**Expected vs Actual:**
| Field | Expected | Actual | Status |
|-------|----------|--------|--------|
| Primary Signal | ${result.test_case.expected_primary_signal} | ${result.actual_primary_signal || 'None'} | ${result.actual_primary_signal === result.test_case.expected_primary_signal ? '✅' : '❌'} |
| Relevance Level | ${result.test_case.expected_relevance_level} | ${result.actual_relevance_level || 'None'} | ${result.actual_relevance_level === result.test_case.expected_relevance_level ? '✅' : '❌'} |
| Evidence Count | ${result.test_case.expected_evidence_count} | ${result.actual_evidence_count} | ${result.actual_evidence_count >= Math.max(1, Math.floor(result.test_case.expected_evidence_count * 0.5)) ? '✅' : '❌'} |
| Confidence | ≥30% | ${(result.signal_confidence * 100).toFixed(1)}% | ${result.signal_confidence >= 0.3 ? '✅' : '❌'} |

**Expected Secondary Signals:** ${result.test_case.expected_secondary_signals.join(', ')}
**Actual Secondary Signals:** ${result.actual_secondary_signals.join(', ')}

**Expected Primary Dimensions:** ${result.test_case.expected_primary_dimensions.join(', ')}
**Actual Primary Dimensions:** ${result.actual_primary_dimensions.join(', ')}

${result.error ? `**Error:** ${result.error}` : ''}

${result.executive_observation ? `**Executive Observation:** ${result.executive_observation}` : ''}

${result.evidence_snippets.length > 0 ? `
**Evidence Trail:**
${result.evidence_snippets.map((snippet: string, i: number) => `${i + 1}. ${snippet}`).join('\n')}
` : ''}

---
`;
}

function generateSignalAnalysis(results: any[]): string {
  const signalCounts: Record<string, { expected: number; actual: number; correct: number }> = {};
  
  results.forEach(result => {
    if (result.error) return;
    
    const expected = result.test_case.expected_primary_signal;
    const actual = result.actual_primary_signal;
    const correct = expected === actual ? 1 : 0;
    
    if (!signalCounts[expected]) {
      signalCounts[expected] = { expected: 0, actual: 0, correct: 0 };
    }
    
    signalCounts[expected].expected++;
    if (actual) signalCounts[expected].actual++;
    signalCounts[expected].correct += correct;
  });
  
  const analysis = Object.entries(signalCounts)
    .map(([signal, counts]) => 
      `- **${signal}:** ${counts.correct}/${counts.expected} correct (${(counts.correct/counts.expected*100).toFixed(1)}%)`
    )
    .join('\n');
  
  return analysis || 'No signal data available';
}

function generateAIDMAAnalysis(results: any[]): string {
  const dimensionCounts: Record<string, { expected: number; actual: number; correct: number }> = {};
  
  results.forEach(result => {
    if (result.error) return;
    
    result.test_case.expected_primary_dimensions.forEach((expectedDim: string) => {
      if (!dimensionCounts[expectedDim]) {
        dimensionCounts[expectedDim] = { expected: 0, actual: 0, correct: 0 };
      }
      
      dimensionCounts[expectedDim].expected++;
      if (result.actual_primary_dimensions.includes(expectedDim)) {
        dimensionCounts[expectedDim].actual++;
        dimensionCounts[expectedDim].correct++;
      }
    });
  });
  
  const analysis = Object.entries(dimensionCounts)
    .map(([dimension, counts]) => 
      `- **${dimension}:** ${counts.correct}/${counts.expected} correct (${(counts.correct/counts.expected*100).toFixed(1)}%)`
    )
    .join('\n');
  
  return analysis || 'No dimension data available';
}

function generateEvidenceAnalysis(results: any[]): string {
  const totalExpected = results.reduce((sum, r) => sum + (r.test_case?.expected_evidence_count || 0), 0);
  const totalActual = results.reduce((sum, r) => sum + (r.actual_evidence_count || 0), 0);
  const avgQuality = totalExpected > 0 ? (totalActual / totalExpected) : 0;
  
  return `
- **Total Expected Evidence:** ${totalExpected}
- **Total Actual Evidence:** ${totalActual}
- **Evidence Quality Score:** ${(avgQuality * 100).toFixed(1)}%
- **Average Evidence per Test:** ${(totalActual / results.length).toFixed(1)}
`;
}

function generateRecommendations(report: any): string {
  const recommendations: string[] = [];
  
  if (report.signal_accuracy < 0.8) {
    recommendations.push('🔧 **Signal Detection:** Review and refine signal extraction patterns and confidence thresholds');
  }
  
  if (report.aidma_accuracy < 0.7) {
    recommendations.push('🗺️ **AIDMA Mapping:** Adjust dimension weightings and mapping logic');
  }
  
  if (report.evidence_quality_score < 0.6) {
    recommendations.push('🔍 **Evidence Quality:** Improve evidence extraction and quality assessment');
  }
  
  if (report.average_processing_time > 10000) {
    recommendations.push('⚡ **Performance:** Optimize pipeline processing time');
  }
  
  if (report.overall_accuracy >= 0.8) {
    recommendations.push('✅ **Production Ready:** System demonstrates sufficient accuracy for production deployment');
  } else {
    recommendations.push('⚠️ **Not Ready:** System needs improvement before production deployment');
  }
  
  return recommendations.length > 0 ? recommendations.join('\n\n') : 'System performance is acceptable';
}

// Run validation if this file is executed directly
if (require.main === module) {
  runValidation().catch(console.error);
}

export { runValidation };
